<?php
/**
 * Plugin Name: Vehicle Transport Estimator
 * Description: Provides a vehicle transport estimate form via shortcode and optional Gutenberg block.
 * Version: 1.0.0
 * Author: Generated by assistant
 * Text Domain: vehicle-transport-estimator
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

define( 'VTE_VERSION', '1.0.0' );
define( 'VTE_DIR', plugin_dir_path( __FILE__ ) );
define( 'VTE_URL', plugin_dir_url( __FILE__ ) );

/* Include files */
require_once VTE_DIR . 'includes/database.php';
require_once VTE_DIR . 'includes/settings.php';
require_once VTE_DIR . 'includes/admin-page.php';

/* Activation hook */
register_activation_hook( __FILE__, 'vte_create_submissions_table' );

/**
 * Returns default options.
 */
function vte_get_defaults() {
    return array(
        'phone' => '+18005551234',
        'next_step_url' => '/quote/step-2',
    );
}

/**
 * Get option with defaults.
 */
function vte_get_option( $key ) {
    $defaults = vte_get_defaults();
    $opts = get_option( 'vte_settings', array() );
    if ( isset( $opts[ $key ] ) && '' !== $opts[ $key ] ) {
        return $opts[ $key ];
    }
    return isset( $defaults[ $key ] ) ? $defaults[ $key ] : '';
}

/**
 * Register assets.
 */
function vte_register_assets() {
    $ver = VTE_VERSION;
    // intl-tel-input library
    wp_register_style( 'intl-tel-input', 'https://cdn.jsdelivr.net/npm/intl-tel-input@23.0.12/build/css/intlTelInput.css', array(), '23.0.12' );
    wp_register_script( 'intl-tel-input', 'https://cdn.jsdelivr.net/npm/intl-tel-input@23.0.12/build/js/intlTelInput.min.js', array(), '23.0.12', true );

    // Plugin assets
    wp_register_style( 'vte-style', VTE_URL . 'assets/css/estimator.css', array('intl-tel-input'), $ver );
    wp_register_script( 'vte-script', VTE_URL . 'assets/js/estimator.js', array('intl-tel-input'), $ver, true );
}
add_action( 'init', 'vte_register_assets' );

/**
 * Shortcode handler.
 */
function vte_shortcode_handler( $atts ) {
    // Ensure assets registered
    if ( ! wp_style_is( 'vte-style', 'registered' ) ) {
        vte_register_assets();
    }

    // Local data
    $states = array( 'Florida', 'New York', 'California', 'Texas', 'Georgia' );

    $estimates = array(
        'Florida|New York' => array(
            'distance' => '~1,250 miles',
            'transit'  => '3–5 days',
            'price'    => '$800 – $1,400',
        ),
        'Florida|California' => array(
            'distance' => '~2,700 miles',
            'transit'  => '7–10 days',
            'price'    => '$2,800 – $4,200',
        ),
        'Florida|Texas' => array(
            'distance' => '~1,100 miles',
            'transit'  => '3–4 days',
            'price'    => '$900 – $1,500',
        ),
        'New York|California' => array(
            'distance' => '~2,900 miles',
            'transit'  => '7–10 days',
            'price'    => '$3,000 – $5,800',
        ),
        'Florida|Georgia' => array(
            'distance' => '~350 miles',
            'transit'  => '1–2 days',
            'price'    => '$900 – $1,300',
        ),
    );

    $phone = vte_get_option( 'phone' );
    $next = vte_get_option( 'next_step_url' );

    wp_enqueue_style( 'vte-style' );
    wp_enqueue_script( 'vte-script' );

    // Escape safe strings for localization
    $phone_esc = esc_js( $phone );
    $next_esc  = esc_js( $next );

    wp_localize_script( 'vte-script', 'vteData', array(
        'states' => $states,
        'estimates' => $estimates,
        'phone' => $phone_esc,
        'nextStepUrl' => $next_esc,
        'ajaxUrl' => admin_url( 'admin-ajax.php' ),
        'nonce' => wp_create_nonce( 'vte_submit_nonce' ),
        'strings' => array(
            'heading' => __( 'Vehicle Transport Estimate', 'vehicle-transport-estimator' ),
            'pickup_label' => __( 'Pick-up State', 'vehicle-transport-estimator' ),
            'dropoff_label' => __( 'Drop-off State', 'vehicle-transport-estimator' ),
            'call_now' => __( 'Call Now!', 'vehicle-transport-estimator' ),
            'next_step' => __( 'Next Step!', 'vehicle-transport-estimator' ),
        ),
    ) );

    ob_start();
    ?>
    <div class="vte-wrap">
        <form class="vte-form" onsubmit="return false;" aria-label="Vehicle transport estimator form">
            <!-- Step 1: Route Selection -->
            <div id="vte-step-1" class="vte-step">
                <div class="vte-select-wrapper">
                    <select id="vte-pickup" class="vte-select" aria-required="true">
                        <option value="">Pick-up State</option>
                    </select>
                </div>

                <div class="vte-select-wrapper">
                    <select id="vte-dropoff" class="vte-select" aria-required="true">
                        <option value="">Drop-off State</option>
                    </select>
                </div>

                <div id="vte-estimate" class="vte-estimate-box" hidden>
                    <div class="vte-estimate-row">
                        <span class="vte-estimate-label">Estimated Price Range:</span>
                        <span class="vte-estimate-value" id="vte-price"></span>
                    </div>
                    <div class="vte-estimate-row">
                        <span class="vte-estimate-label">Estimated Distance:</span>
                        <span class="vte-estimate-value" id="vte-distance"></span>
                    </div>
                    <div class="vte-estimate-row">
                        <span class="vte-estimate-label">Estimated Transit Time:</span>
                        <span class="vte-estimate-value" id="vte-transit"></span>
                    </div>
                    <p class="vte-disclaimer">* Prices varies by vehicle size, pickup location, fuel economy cost and season</p>
                </div>

                <div id="vte-message" class="vte-message-box" role="status" aria-live="polite" hidden>
                    <p id="vte-message-text"></p>
                </div>

                <div class="vte-actions">
                    <a id="vte-call" class="vte-btn vte-btn-call" href="#">
                        <svg class="vte-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
                        </svg>
                        Call Now!
                    </a>
                    <button id="vte-next" class="vte-btn vte-btn-next" type="button">
                        <svg class="vte-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                        Next Step
                    </button>
                </div>
            </div>

            <!-- Step 2: User Information -->
            <div id="vte-step-2" class="vte-step" hidden>
                <div class="vte-input-wrapper">
                    <input type="text" id="vte-fullname" class="vte-input" placeholder="Full Name" required>
                </div>

                <div class="vte-input-wrapper">
                    <input type="tel" id="vte-phone" class="vte-input" placeholder="Phone number" required>
                </div>

                <div class="vte-input-wrapper">
                    <input type="email" id="vte-email" class="vte-input" placeholder="Email Address" required>
                </div>

                <div class="vte-actions vte-actions-center">
                    <button id="vte-submit" class="vte-btn vte-btn-next vte-btn-submit" type="submit">
                        <svg class="vte-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                        Next Step
                    </button>
                </div>
            </div>
        </form>
    </div>
    <?php
    return ob_get_clean();
}
add_shortcode( 'vehicle_transport_estimator', 'vte_shortcode_handler' );

/**
 * AJAX handler for form submission.
 */
function vte_ajax_submit_form() {
    // Verify nonce
    check_ajax_referer( 'vte_submit_nonce', 'nonce' );

    // Get form data
    $fullname = isset( $_POST['fullname'] ) ? sanitize_text_field( $_POST['fullname'] ) : '';
    $phone = isset( $_POST['phone'] ) ? sanitize_text_field( $_POST['phone'] ) : '';
    $email = isset( $_POST['email'] ) ? sanitize_email( $_POST['email'] ) : '';

    // Get route data
    $pickup = isset( $_POST['pickup'] ) ? sanitize_text_field( $_POST['pickup'] ) : '';
    $dropoff = isset( $_POST['dropoff'] ) ? sanitize_text_field( $_POST['dropoff'] ) : '';
    $price = isset( $_POST['price'] ) ? sanitize_text_field( $_POST['price'] ) : '';
    $distance = isset( $_POST['distance'] ) ? sanitize_text_field( $_POST['distance'] ) : '';
    $transit = isset( $_POST['transit'] ) ? sanitize_text_field( $_POST['transit'] ) : '';

    // Validate required fields
    if ( empty( $fullname ) || empty( $phone ) || empty( $email ) ) {
        wp_send_json_error( array(
            'message' => __( 'Please fill in all required fields.', 'vehicle-transport-estimator' )
        ) );
        return;
    }

    if ( empty( $pickup ) || empty( $dropoff ) ) {
        wp_send_json_error( array(
            'message' => __( 'Route information is missing.', 'vehicle-transport-estimator' )
        ) );
        return;
    }

    // Save to database
    $submission_data = array(
        'fullname' => $fullname,
        'phone' => $phone,
        'email' => $email,
        'pickup' => $pickup,
        'dropoff' => $dropoff,
        'price' => $price,
        'distance' => $distance,
        'transit' => $transit,
    );

    $submission_id = vte_save_submission( $submission_data );

    // Prepare webhook payload
    $payload = array(
        'id' => $submission_id,
        'fullname' => $fullname,
        'phone' => $phone,
        'email' => $email,
        'route' => array(
            'pickup' => $pickup,
            'dropoff' => $dropoff,
            'price' => $price,
            'distance' => $distance,
            'transit' => $transit,
        ),
        'timestamp' => current_time( 'mysql' ),
        'source' => 'vehicle-transport-estimator',
    );

    // Get webhook URL from settings
    $webhook_url = vte_get_option( 'webhook_url' );

    if ( ! empty( $webhook_url ) ) {
        // Send webhook
        $response = wp_remote_post( $webhook_url, array(
            'headers' => array(
                'Content-Type' => 'application/json',
            ),
            'body' => wp_json_encode( $payload ),
            'timeout' => 15,
            'sslverify' => true,
        ) );

        // Check for errors
        if ( is_wp_error( $response ) ) {
            wp_send_json_error( array(
                'message' => __( 'Failed to send webhook. Please try again.', 'vehicle-transport-estimator' ),
                'error' => $response->get_error_message(),
            ) );
            return;
        }

        $response_code = wp_remote_retrieve_response_code( $response );
        if ( $response_code < 200 || $response_code >= 300 ) {
            wp_send_json_error( array(
                'message' => __( 'Webhook returned an error. Please try again.', 'vehicle-transport-estimator' ),
                'code' => $response_code,
            ) );
            return;
        }
    }

    // Success response
    wp_send_json_success( array(
        'message' => __( 'Form submitted successfully!', 'vehicle-transport-estimator' ),
        'redirect' => vte_get_option( 'next_step_url' ),
    ) );
}
add_action( 'wp_ajax_vte_submit_form', 'vte_ajax_submit_form' );
add_action( 'wp_ajax_nopriv_vte_submit_form', 'vte_ajax_submit_form' );
